import { useMutation, useQuery } from "@tanstack/react-query";
import { Brain, Lightbulb } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { LoadingState } from "@/components/ui/loading-state";
import { ProductSearchPicker } from "@/features/products/product-search-picker";
import { Product, api } from "@/lib/api";

export function AdvisorPage() {
  const [searchParams, setSearchParams] = useSearchParams();
  const productId = searchParams.get("productId") ?? "";
  const shouldGenerate = searchParams.get("generate") === "1";
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const autoGeneratedProductRef = useRef<string | null>(null);
  const selectedProductQuery = useQuery({
    queryKey: ["products", productId],
    queryFn: () => api.product(productId),
    enabled: Boolean(productId),
  });
  const advisor = useMutation({
    mutationFn: (id: string) => api.advisor(id),
    meta: {
      successMessage: "Sustainability analysis generated",
      errorMessage: "Could not generate sustainability analysis",
    },
  });
  const generateAdvisorRef = useRef(advisor.mutate);

  useEffect(() => {
    generateAdvisorRef.current = advisor.mutate;
  }, [advisor.mutate]);

  useEffect(() => {
    if (selectedProductQuery.data) {
      setSelectedProduct(selectedProductQuery.data);
    }
  }, [selectedProductQuery.data]);

  useEffect(() => {
    if (!productId || !shouldGenerate || autoGeneratedProductRef.current === productId) return;
    const timer = window.setTimeout(() => {
      autoGeneratedProductRef.current = productId;
      generateAdvisorRef.current(productId);
    }, 0);
    return () => window.clearTimeout(timer);
  }, [productId, shouldGenerate]);

  const selectProduct = (product: Product) => {
    autoGeneratedProductRef.current = null;
    setSelectedProduct(product);
    setSearchParams({ productId: product.id });
  };

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-semibold">AI Sustainability Advisor</h1>
        <p className="text-sm text-muted-foreground">Product-specific recommendations, not a chatbot.</p>
      </div>
      <section className="rounded-lg border border-border bg-card p-5">
        <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-start">
          {selectedProductQuery.isLoading ? (
            <LoadingState label="Loading selected product" />
          ) : (
            <ProductSearchPicker selectedProduct={selectedProduct} onSelect={selectProduct} />
          )}
          <Button disabled={!productId || advisor.isPending} onClick={() => advisor.mutate(productId)}>
            <Brain size={16} /> Analyze product
          </Button>
        </div>
      </section>
      {advisor.isPending ? (
        <LoadingState label="Generating sustainability recommendations" />
      ) : advisor.data?.recommendations.length ? (
        <div className="grid gap-4 lg:grid-cols-2">
          {advisor.data.recommendations.map((rec) => (
            <article key={rec.title} className="rounded-lg border border-border bg-card p-5">
              <div className="mb-3 flex items-center gap-2 text-primary"><Lightbulb size={18} /><span className="text-sm font-semibold">{rec.impact} impact</span></div>
              <h2 className="font-semibold">{rec.title}</h2>
              <p className="mt-2 text-sm text-muted-foreground">{rec.rationale}</p>
              <p className="mt-4 text-sm font-medium">{rec.next_step}</p>
            </article>
          ))}
        </div>
      ) : advisor.data ? (
        <EmptyState title="No recommendations found">
          This product is already within the local advisory thresholds.
        </EmptyState>
      ) : (
        <EmptyState title="No analysis selected">Choose a product to generate recommendations.</EmptyState>
      )}
    </div>
  );
}
