import { useMutation, useQuery } from "@tanstack/react-query";
import { Brain, Lightbulb, ShieldCheck } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { LoadingState } from "@/components/ui/loading-state";
import { ProductSearchPicker } from "@/features/products/product-search-picker";
import { AdvisorResult, Product, api } from "@/lib/api";
import { useToastStore } from "@/stores/toast-store";

export function AdvisorPage() {
  const [searchParams, setSearchParams] = useSearchParams();
  const productId = searchParams.get("productId") ?? "";
  const shouldGenerate = searchParams.get("generate") === "1";
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const [jobId, setJobId] = useState<string | null>(null);
  const [advisorResult, setAdvisorResult] = useState<AdvisorResult | null>(null);
  const autoGeneratedProductRef = useRef<string | null>(null);
  const addToast = useToastStore((state) => state.addToast);
  const selectedProductQuery = useQuery({
    queryKey: ["products", productId],
    queryFn: () => api.product(productId),
    enabled: Boolean(productId),
  });
  const advisor = useMutation({
    mutationFn: (id: string) => api.startAdvisorJob(id),
    onSuccess: (job) => {
      setJobId(job.id);
      setAdvisorResult(null);
    },
    meta: {
      successMessage: "Sustainability analysis started",
      errorMessage: "Could not generate sustainability analysis",
    },
  });
  const job = useQuery({
    queryKey: ["ai-job", jobId],
    queryFn: () => api.aiJob(jobId ?? ""),
    enabled: Boolean(jobId),
    refetchInterval: (query) => {
      const status = query.state.data?.status;
      return status === "pending" || status === "running" ? 1500 : false;
    },
  });
  const generateAdvisorRef = useRef(advisor.mutate);

  useEffect(() => {
    generateAdvisorRef.current = advisor.mutate;
  }, [advisor.mutate]);

  useEffect(() => {
    if (selectedProductQuery.data) {
      setSelectedProduct(selectedProductQuery.data);
    }
  }, [selectedProductQuery.data]);

  useEffect(() => {
    if (!job.data) return;
    if (job.data.status === "succeeded" && job.data.result_json) {
      setAdvisorResult(job.data.result_json as AdvisorResult);
      setJobId(null);
      addToast({ title: "Sustainability analysis generated", variant: "success" });
    }
    if (job.data.status === "failed") {
      setJobId(null);
      addToast({
        title: "Analysis failed",
        description: job.data.error_message ?? "The AI job could not be completed.",
        variant: "error",
      });
    }
  }, [addToast, job.data]);

  useEffect(() => {
    if (!productId || !shouldGenerate || autoGeneratedProductRef.current === productId) return;
    const timer = window.setTimeout(() => {
      autoGeneratedProductRef.current = productId;
      generateAdvisorRef.current(productId);
    }, 0);
    return () => window.clearTimeout(timer);
  }, [productId, shouldGenerate]);

  const selectProduct = (product: Product) => {
    autoGeneratedProductRef.current = null;
    setSelectedProduct(product);
    setAdvisorResult(null);
    setJobId(null);
    setSearchParams({ productId: product.id });
  };

  const isGenerating =
    advisor.isPending || job.data?.status === "pending" || job.data?.status === "running";

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-semibold">AI Sustainability Advisor</h1>
        <p className="text-sm text-muted-foreground">Product-specific recommendations, not a chatbot.</p>
      </div>
      <section className="rounded-lg border border-border bg-card p-5">
        <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-start">
          {selectedProductQuery.isLoading ? (
            <LoadingState label="Loading selected product" />
          ) : (
            <ProductSearchPicker selectedProduct={selectedProduct} onSelect={selectProduct} />
          )}
          <Button disabled={!productId || isGenerating} onClick={() => advisor.mutate(productId)}>
            <Brain size={16} /> Analyze product
          </Button>
        </div>
      </section>
      {isGenerating ? (
        <LoadingState label="Generating sustainability recommendations" />
      ) : advisorResult?.recommendations.length ? (
        <>
          <AISafetyBanner provider={advisorResult.provider} safety={advisorResult.safety} />
          <div className="grid gap-4 lg:grid-cols-2">
            {advisorResult.recommendations.map((rec) => (
              <article key={rec.title} className="rounded-lg border border-border bg-card p-5">
                <div className="mb-3 flex items-center gap-2 text-primary"><Lightbulb size={18} /><span className="text-sm font-semibold">{rec.impact} impact</span></div>
                <h2 className="font-semibold">{rec.title}</h2>
                <p className="mt-2 text-sm text-muted-foreground">{rec.rationale}</p>
                <p className="mt-4 text-sm font-medium">{rec.next_step}</p>
              </article>
            ))}
          </div>
        </>
      ) : advisorResult ? (
        <EmptyState title="No recommendations found">
          This product is already within the local advisory thresholds.
        </EmptyState>
      ) : (
        <EmptyState title="No analysis selected">Choose a product to generate recommendations.</EmptyState>
      )}
    </div>
  );
}

function AISafetyBanner({ provider, safety }: { provider: string; safety: AdvisorResult["safety"] }) {
  return (
    <section className="rounded-lg border border-border bg-card p-4 text-sm">
      <div className="flex flex-wrap items-center gap-2">
        <span className="inline-flex items-center gap-2 font-medium text-primary">
          <ShieldCheck size={16} /> AI safety validated
        </span>
        <span className="rounded-full bg-muted px-2 py-1 text-xs text-muted-foreground">{provider}</span>
        <span className="rounded-full bg-muted px-2 py-1 text-xs text-muted-foreground">{safety.execution_mode}</span>
        <span className="rounded-full bg-muted px-2 py-1 text-xs text-muted-foreground">{safety.policy_version}</span>
      </div>
      <p className="mt-2 text-muted-foreground">{safety.data_policy}</p>
    </section>
  );
}
