import { useMutation, useQuery } from "@tanstack/react-query";
import { Clipboard, Download, FileText, ShieldCheck } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { LoadingState } from "@/components/ui/loading-state";
import { ProductSearchPicker } from "@/features/products/product-search-picker";
import { Product, ReportResult, api } from "@/lib/api";
import { useToastStore } from "@/stores/toast-store";

export function ReportsPage() {
  const [searchParams, setSearchParams] = useSearchParams();
  const productId = searchParams.get("productId") ?? "";
  const shouldGenerate = searchParams.get("generate") === "1";
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const [jobId, setJobId] = useState<string | null>(null);
  const [reportResult, setReportResult] = useState<ReportResult | null>(null);
  const autoGeneratedProductRef = useRef<string | null>(null);
  const selectedProductQuery = useQuery({
    queryKey: ["products", productId],
    queryFn: () => api.product(productId),
    enabled: Boolean(productId),
  });
  const addToast = useToastStore((state) => state.addToast);
  const report = useMutation({
    mutationFn: (id: string) => api.startReportJob(id),
    onSuccess: (job) => {
      setJobId(job.id);
      setReportResult(null);
    },
    meta: {
      successMessage: "Executive report started",
      errorMessage: "Could not generate report",
    },
  });
  const job = useQuery({
    queryKey: ["ai-job", jobId],
    queryFn: () => api.aiJob(jobId ?? ""),
    enabled: Boolean(jobId),
    refetchInterval: (query) => {
      const status = query.state.data?.status;
      return status === "pending" || status === "running" ? 1500 : false;
    },
  });
  const generateReportRef = useRef(report.mutate);

  useEffect(() => {
    generateReportRef.current = report.mutate;
  }, [report.mutate]);

  useEffect(() => {
    if (selectedProductQuery.data) {
      setSelectedProduct(selectedProductQuery.data);
    }
  }, [selectedProductQuery.data]);

  useEffect(() => {
    if (!job.data) return;
    if (job.data.status === "succeeded" && job.data.result_json) {
      setReportResult(job.data.result_json as ReportResult);
      setJobId(null);
      addToast({ title: "Executive report generated", variant: "success" });
    }
    if (job.data.status === "failed") {
      setJobId(null);
      addToast({
        title: "Report failed",
        description: job.data.error_message ?? "The AI job could not be completed.",
        variant: "error",
      });
    }
  }, [addToast, job.data]);

  useEffect(() => {
    if (!productId || !shouldGenerate || autoGeneratedProductRef.current === productId) return;
    const timer = window.setTimeout(() => {
      autoGeneratedProductRef.current = productId;
      generateReportRef.current(productId);
    }, 0);
    return () => window.clearTimeout(timer);
  }, [productId, shouldGenerate]);

  const selectProduct = (product: Product) => {
    autoGeneratedProductRef.current = null;
    setSelectedProduct(product);
    setReportResult(null);
    setJobId(null);
    setSearchParams({ productId: product.id });
  };

  const downloadReport = () => {
    if (!reportResult || !selectedProduct) return;
    const blob = new Blob([reportResult.markdown], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `${selectedProduct.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-sustainability-report.md`;
    anchor.click();
    URL.revokeObjectURL(url);
    addToast({ title: "Report downloaded", variant: "success" });
  };
  const copyReport = async () => {
    if (!reportResult) return;
    await navigator.clipboard.writeText(reportResult.markdown);
    addToast({ title: "Report copied", variant: "success" });
  };
  const isGenerating =
    report.isPending || job.data?.status === "pending" || job.data?.status === "running";

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-semibold">AI Report Generator</h1>
        <p className="text-sm text-muted-foreground">
          Generate executive sustainability summaries from product environmental records.
        </p>
      </div>

      <section className="rounded-lg border border-border bg-card p-5">
        {selectedProductQuery.isLoading ? (
          <LoadingState label="Loading selected product" />
        ) : (
          <div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_auto]">
            <ProductSearchPicker selectedProduct={selectedProduct} onSelect={selectProduct} />
            <Button disabled={!productId || isGenerating} onClick={() => report.mutate(productId)}>
              <FileText size={16} /> Generate report
            </Button>
          </div>
        )}
      </section>

      {isGenerating ? (
        <LoadingState label="Generating executive report" />
      ) : reportResult ? (
        <section className="rounded-lg border border-border bg-card p-5">
          <div className="mb-5 flex flex-col justify-between gap-3 md:flex-row md:items-start">
            <div>
              <h2 className="font-semibold">{selectedProduct?.name ?? "Sustainability Report"}</h2>
              <p className="mt-1 text-sm text-muted-foreground">{reportResult.summary}</p>
              <div className="mt-3 flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
                <span className="inline-flex items-center gap-1 rounded-full bg-primary/10 px-2 py-1 text-primary">
                  <ShieldCheck size={13} /> {reportResult.safety.status}
                </span>
                <span className="rounded-full bg-muted px-2 py-1">{reportResult.provider}</span>
                <span className="rounded-full bg-muted px-2 py-1">{reportResult.safety.execution_mode}</span>
                <span className="rounded-full bg-muted px-2 py-1">{reportResult.safety.policy_version}</span>
              </div>
            </div>
            <div className="flex gap-2">
              <Button variant="secondary" onClick={copyReport}>
                <Clipboard size={16} /> Copy
              </Button>
              <Button onClick={downloadReport}>
                <Download size={16} /> Download
              </Button>
            </div>
          </div>
          <article className="whitespace-pre-wrap rounded-md border border-border bg-muted/40 p-4 text-sm leading-6">
            {reportResult.markdown}
          </article>
        </section>
      ) : (
        <EmptyState title="No report generated">
          Select a product to create an executive sustainability report.
        </EmptyState>
      )}
    </div>
  );
}
